// <auto-generated />
using System;
using FitnessCenterManagement.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessCenterManagement.Web.Migrations
{
    [DbContext(typeof(FitnessCenterDbContext))]
    partial class FitnessCenterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessCenterManagement.Web.Models.Antrenor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan?>("MevcutBaslangicSaati")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("MevcutBitisSaati")
                        .HasColumnType("time");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SporSalonuId")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UzmanlıkAlanlari")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SporSalonuId");

                    b.ToTable("Antrenorler");
                });

            modelBuilder.Entity("FitnessCenterManagement.Web.Models.Hizmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SporSalonuId")
                        .HasColumnType("int");

                    b.Property<int>("SureDakika")
                        .HasColumnType("int");

                    b.Property<decimal>("Ucret")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SporSalonuId");

                    b.ToTable("Hizmetler");
                });

            modelBuilder.Entity("FitnessCenterManagement.Web.Models.Randevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AntrenorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BaslamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Beklemede");

                    b.Property<int>("HizmetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Ucret")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UyeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AntrenorId")
                        .HasDatabaseName("IX_Randevu_AntrenorId");

                    b.HasIndex("HizmetId")
                        .HasDatabaseName("IX_Randevu_HizmetId");

                    b.HasIndex("UyeId")
                        .HasDatabaseName("IX_Randevu_UyeId");

                    b.HasIndex("BaslamaTarihi", "BitisTarihi")
                        .HasDatabaseName("IX_Randevu_TarihAraligi");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("FitnessCenterManagement.Web.Models.SporSalonu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CalismaZamanlari")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SporSalonlari");
                });

            modelBuilder.Entity("FitnessCenterManagement.Web.Models.Uye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("AgirlikKilogram")
                        .HasColumnType("int");

                    b.Property<int?>("BouSantimetre")
                        .HasColumnType("int");

                    b.Property<string>("Cinsiyet")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("FitnessHedefi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId")
                        .IsUnique()
                        .HasDatabaseName("IX_Uye_KullaniciId");

                    b.ToTable("Uyeler");
                });

            modelBuilder.Entity("FitnessCenterManagement.Web.Models.YapayzekaTavsiye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CevapTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("CiktiVeri")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GirdiVeri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HataMesaji")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IslemBasarili")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("TavsiyeTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UyeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UyeId");

                    b.ToTable("YapayzekaTavsiyeler");
                });

            modelBuilder.Entity("FitnessCenterManagement.Web.Models.Antrenor", b =>
                {
                    b.HasOne("FitnessCenterManagement.Web.Models.SporSalonu", "SporSalonu")
                        .WithMany("Antrenorler")
                        .HasForeignKey("SporSalonuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Antrenor_SporSalonu");

                    b.Navigation("SporSalonu");
                });

            modelBuilder.Entity("FitnessCenterManagement.Web.Models.Hizmet", b =>
                {
                    b.HasOne("FitnessCenterManagement.Web.Models.SporSalonu", "SporSalonu")
                        .WithMany("Hizmetler")
                        .HasForeignKey("SporSalonuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Hizmet_SporSalonu");

                    b.Navigation("SporSalonu");
                });

            modelBuilder.Entity("FitnessCenterManagement.Web.Models.Randevu", b =>
                {
                    b.HasOne("FitnessCenterManagement.Web.Models.Antrenor", "Antrenor")
                        .WithMany("Randevular")
                        .HasForeignKey("AntrenorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Randevu_Antrenor");

                    b.HasOne("FitnessCenterManagement.Web.Models.Hizmet", "Hizmet")
                        .WithMany("Randevular")
                        .HasForeignKey("HizmetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Randevu_Hizmet");

                    b.HasOne("FitnessCenterManagement.Web.Models.Uye", "Uye")
                        .WithMany("Randevular")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Randevu_Uye");

                    b.Navigation("Antrenor");

                    b.Navigation("Hizmet");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("FitnessCenterManagement.Web.Models.YapayzekaTavsiye", b =>
                {
                    b.HasOne("FitnessCenterManagement.Web.Models.Uye", "Uye")
                        .WithMany("YapayzekaTavsiyeler")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_YapayzekaTavsiye_Uye");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("FitnessCenterManagement.Web.Models.Antrenor", b =>
                {
                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("FitnessCenterManagement.Web.Models.Hizmet", b =>
                {
                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("FitnessCenterManagement.Web.Models.SporSalonu", b =>
                {
                    b.Navigation("Antrenorler");

                    b.Navigation("Hizmetler");
                });

            modelBuilder.Entity("FitnessCenterManagement.Web.Models.Uye", b =>
                {
                    b.Navigation("Randevular");

                    b.Navigation("YapayzekaTavsiyeler");
                });
#pragma warning restore 612, 618
        }
    }
}
